/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
desplegable ={
    "_id": 0,
    "perfil": {
        "10": "Consulta",
        "30": "Alumno",
        "50": "Profesor",
        "90": "Administrador"
    },
    "cadena": {
        "1": "TVE",
        "2": "LA SEXTA",
        "3": "T5",
        "4": "A3",
        "5": "CUATRO"
    },
    "semestre": {
        "1": "S1",
        "2": "S2"
    },
    "edicion": {
        "1": "MEDIODÍA",
        "2": "VESPERTINA"
    },
    "format": {
        "1": "PRESENTACIONES",
        "2": "COLAS",
        "3": "ENT+VTR",
        "4": "DIRECTO",
        "5": "VTR",
        "6": "BREVES",
        "7": "PRESENTACIÓN INFOGRÁFICA"
    },
    "dqcategoria": {
        "1": "Política España general",
        "2": "Partidos políticos España",
        "3": "Elecciones en España",
        "4": "Corrupción política España",
        "5": "Política autónomica España",
        "6": "Protestas España",
        "7": "Seguridad ciudadana España",
        "8": "Política exterior España",
        "9": "Administración y servicios públicos España",
        "10": "Terrorismo en España",
        "11": "Defensa España",
        "12": "Justicia España",
        "13": "Política UE",
        "14": "Política países extranjeros",
        "15": "Conflicto interno países extranjeros",
        "16": "Diplomacia y relaciones internacionales",
        "17": "Guerra y conflictos internacionales",
        "18": "Terrorismo internacional",
        "19": "Empresas: Actividad empresas. Nacional e internac.",
        "20": "Comercio: Intercambios económicos. Import/export.",
        "21": "Impuestos: tributos, tasas, reformas tributarias.",
        "22": "Trabajo, empleo y paro",
        "23": "Consumo",
        "24": "Finanzas: Bancos, bolsa, dinero",
        "25": "Seguridad Social",
        "26": "Industria: Producción, reconversiones\u2026",
        "27": "Infraestructuras: presas, carreteras\u2026",
        "28": "Urbanismo: legislacion, vivienda, construcción\u2026",
        "29": "Medicina y Sanidad: enfermedades, investigación\u2026",
        "30": "Drogas",
        "31": "Religión",
        "32": "Ciencia y técnica",
        "33": "Medio ambiente: Conservación, contaminación\u2026",
        "34": "Catástrofes y accidentes",
        "35": "Crímenes y delitos.",
        "36": "Famosos y corazón: Información 'rosa'",
        "37": "Educación",
        "38": "Mujer: condición de la mujer, violencia, derechos",
        "39": "Menores: infancia, condición de los menores\u2026",
        "40": "LGT: Lesbianas, gays y transexuales.",
        "41": "Familia",
        "42": "Discapacidad",
        "43": "Fenómenos migratorios",
        "44": "Desarrollo: Desarrollo y subdesarrollo económico",
        "45": "Gastronomía y alimentación",
        "46": "Moda: Desfiles, modelos, modistos.",
        "47": "Estilo de vida y tendencias: Dietas, cuidados\u2026",
        "48": "Fiestas populares: Nacional e internacional.",
        "49": "Curiosidades y hechos llamativos",
        "50": "Derechos humanos: Violaciones de los derechos hh.",
        "51": "Táfico y coches: Modelos, empresas del automóv\u2026",
        "52": "El tiempo",
        "53": "Servicios sociales",
        "54": "Demografía y población. Nacional e internacional",
        "55": "Jóvenes: costumbres, hábitos, comportamientos.",
        "56": "Ancianos: geriatría, procesos de envejecimiento\u2026",
        "57": "Eutanasia: muerte digna, testamento vital, leyes..",
        "58": "Sociedad de la Información: Internet, periodismo",
        "59": "Turismo: activides, lugares, empresas.",
        "60": "Hábitos de vida: costumbres, horarios.",
        "61": "Movimientos sociales: activismo ciudadano.",
        "62": "Literatura: Libros, críticas literarias, premios.",
        "63": "Lengua: Academias de la lengua, Inst. Cervantes",
        "64": "Cine: Películas, estrenos, críticas, industria\u2026",
        "65": "Teatro: Obras, estrenos, críticas, premios.",
        "66": "Artes plásticas: Pintura, escultura, grabado.",
        "67": "Arquitectura: Edificios, concursos, premios.",
        "68": "Videojuegos",
        "69": "Musica pop: Lanzamientos, críticas, grupos\u2026",
        "70": "Música folk: Música folclórica, de raíz, étnica.",
        "71": "Flamenco y copla. Nacional e internacional",
        "72": "Jazz",
        "73": "Música clásica y ópera",
        "74": "Danza y ballet",
        "75": "Industrias culturales",
        "76": "Televisión: programas, tendencias, cadenas\u2026",
        "77": "Toros: espectáculos, toreros, polémica.",
        "78": "Historia: recuerdos, efemérides.Nacional e intern.",
        "79": "Fútbol",
        "80": "Baloncesto",
        "81": "Balonmano",
        "82": "Tenis",
        "83": "Automovilismo",
        "84": "Motociclismo",
        "85": "Ciclismo",
        "86": "Deportes de invierno y montaña",
        "87": "Golf",
        "88": "Olimpismo: Movimiento olímpico, juegos olímpicos",
        "89": "Otros deportes",
        "90": "Otros temas (diferentes a los indicados)",
        "91": "Proceso legislativo España"
    },
    "genero": {
        "1": "Noticia",
        "2": "Informe",
        "3": "Crónica",
        "4": "Reportaje",
        "5": "Entrevista",
        "6": "Encuesta",
        "7": "Declaraciones"
    },
    "ambito": {
        "1": "Nacional",
        "2": "Internacional",
        "3": "Global",
        "4": "Local"
    },
    "zona": {
        "1": "UE",
        "2": "Europa Oriental",
        "3": "Balcanes",
        "4": "Oriente Próximo",
        "5": "Espacio Postsoviético",
        "6": "Oriente Medio",
        "7": "Magreb",
        "8": "Sahel",
        "9": "África Subsahariana",
        "10": "Latinoamérica",
        "11": "Extremo Oriente",
        "12": "Asia Central",
        "13": "Escandinavia",
        "14": "Países Árabes",
        "15": "Norteamérica"
    },
    "categoria": {
        "1": "Jefe del Estado España",
        "2": "Jefe del Estado Extranjero: rey, presidente de la República",
        "3": "Gobierno España: presidente del gobierno y ministros. Incluye hasta secretarios de estado.",
        "4": "Gobierno extranjero: presidente del gobierno, primer ministro, ministros.",
        "5": "Partidos del gobierno España: partido o partidos que sostienen al gobierno.",
        "6": "Partidos del gobierno extranjero: partido o partidos que sostienen al gobierno.",
        "7": "Principal partido de la oposición España: partido más importante entre los de la oposición.",
        "8": "Otros partidos de la oposición España: resto de los partidos de la oposición.",
        "9": "Partidos oposición extranjero: todos los partidos de la oposición",
        "10": "Gobierno comunidades autónomas: presidente, consejeros, partidos que apoyan.",
        "11": "Partidos de la oposición de las comunidades autónomas",
        "12": "Partidos de la oposición de las comunidades autónomas",
        "13": "Jueces y fiscales: miembros de tribunales personales o colegiados y de la organización judicial y sus órganos de gobierno. Nacional e internacional.",
        "14": "Autoridades independientes: miembros de consejos asesores, o de consejos reguladores de actividades económicas. Naciona e internacional",
        "15": "Alcaldes y concejales: miembros de las corporaciones locales. Nacional e internacional.",
        "16": "Autoridades UE: miembros de la comisión (comisarios), presidente del consejo de la UE.",
        "17": "Autoridades ONU: secretario general de la ONU y altos funcionarios de la ONU y de sus organizaciones filiales (UNICEF, FAO, ACNUR etc.)",
        "18": "Embajadores y diplomáticos: representantes de los países en otros países y en organizaciones internacionales. Nacional e internacional.",
        "19": "Sindicatos y trabajadores: miembros de las organizaciones sindicales y trabajadores y trabajadores individuales. Nacional e internacional.",
        "20": "Organizaciones empresariales y empresarios: miembros de la organizaciones empresariales y empresarios individuales. Nacional e internacional.",
        "21": "Iglesias y religiosos: autoridades religiosas y ministros de cualquier confesión. Nacional e internacional.",
        "22": "ONGs: miembros de organizaciones no gubernamentales de asistencia, ayuda al desarrollo o derechos humanos. Nacional e internacional.",
        "23": "Consumidores: miembros de la organizaciones de consumidores o ciudadanos individuales en su función de consumidores. Nacional e internacional.",
        "24": "Movimientos sociales: miembros de asociaciones y grupos informales de todo tipo. Nacional e internacional.",
        "25": "Policías: miembros de las fuerzas y cuerpos de seguridad y sus mandos. Nacional e internacional.",
        "26": "Militares: miembros de las fuerzas armadas (ejércitos de tierra, marina y aire)y sus mandos. Nacional e internacional.",
        "27": "Científicos y académicos: investigadores y docentes de disciplinas científicas, humanidades y ciencias sociales. Nacional e internacional.",
        "28": "Profesionales: médicos, abogados, arquitectos, periodistas, ingenieros, psicólogos, sociólogos etc. Nacional e internacional.",
        "29": "Artistas: cantantes, músicos, actores, cineastas, pintores. escultores, profesionales del teatro. Nacional e internacional.",
        "30": "Deportistas, federaciones y organizaciones deportivas. Nacional e internacional.",
        "31": "Ciudadanos: individuos que hablan o son mencionados sin una función especial. Nacional e internacional."
    },
    "catTem": {
        "1": "Nacional",
        "2": "Internacional",
        "3": "Economía",
        "4": "Sociedad",
        "5": "Cultura",
        "6": "Deportes",
        "7": "Otras"
    },
    "relcad": {
        "1": "Autopromoción de programas de la cadena",
        "2": "Actividades institucionales de la cadena",
        "3": "Toma de postura editorial",
        "4": "Campañas pro causa"
    },
    "valedit": {
        "1": "Apertura",
        "2": "Sumario principal",
        "3": "Sumario secundario",
        "4": "Apertura de bloque",
        "5": "Bloque temático",
        "6": "Sin destacar"
    },
    "origen": {
        "1": "Imagen de actualidad",
        "2": "Imagen de archivo",
        "3": "Imagen escenificada",
        "4": "Imagen de síntesis",
        "5": "Vídeos de Internet",
        "6": "Imagen de estudio"
    },
    "rotulos": {
        "1": "Localización",
        "2": "Identificación",
        "3": "Informativo",
        "4": "Técnico",
        "5": "Editorial"
    },
    "informador": {
        "1": "Narrador externo",
        "2": "Testigo",
        "3": "Protagonista"
    },
    "retorica": {
        "1": "Imagen violenta",
        "2": "Imagen dramática",
        "3": "Imagen emotiva",
        "4": "Imagen de acción",
        "5": "Imagen estética",
        "6": "Imagen simbólica",
        "7": "Imagen enfática",
        "8": "Imagen neutral"
    },
    "comunidad": {
        "ES-AN": "Andalucía",
        "ES-AR": "Aragón",
        "ES-O": "Principado de Asturias",
        "ES-CN": "Canarias",
        "ES-S": "Cantabria",
        "ES-CM": "Castilla-La Mancha",
        "ES-CL": "Castilla y León",
        "ES-CT": "Cataluña",
        "ES-EX": "Extremadura",
        "ES-GA": "Galicia",
        "ES-PM": "Islas Baleares",
        "ES-LO": "La Rioja",
        "ES-M": "Comunidad de Madrid",
        "ES-MU": "Murcia, Región de",
        "ES-NA": "Comunidad Foral de Navarra",
        "ES-PV": "País Vasco",
        "ES-VC": "Comunidad Valenciana",
        "ES-CE": "Ceuta",
        "ES-ME": "Melilla"
    },
    "pais": {
        "AF": "Afganistán",
        "AL": "Albania",
        "DE": "Alemania",
        "DZ": "Algeria",
        "AD": "Andorra",
        "AO": "Angola",
        "AI": "Anguila",
        "AQ": "Antártida",
        "AG": "Antigua y Barbuda",
        "AN": "Antillas Neerlandesas",
        "SA": "Arabia Saudita",
        "AR": "Argentina",
        "AM": "Armenia",
        "AW": "Aruba",
        "AU": "Australia",
        "AT": "Austria",
        "AZ": "Azerbayán",
        "BE": "Bélgica",
        "BS": "Bahamas",
        "BH": "Bahrein",
        "BD": "Bangladesh",
        "BB": "Barbados",
        "BZ": "Belice",
        "BJ": "Benín",
        "BT": "Bhután",
        "BY": "Bielorrusia",
        "MM": "Birmania",
        "BO": "Bolivia",
        "BA": "Bosnia y Herzegovina",
        "BW": "Botsuana",
        "BR": "Brasil",
        "BN": "Brunéi",
        "BG": "Bulgaria",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "CV": "Cabo Verde",
        "KH": "Camboya",
        "CM": "Camerún",
        "CA": "Canadá",
        "TD": "Chad",
        "CL": "Chile",
        "CN": "China",
        "CY": "Chipre",
        "VA": "Ciudad del Vaticano",
        "CO": "Colombia",
        "KM": "Comoras",
        "CG": "Congo",
        "CD": "Congo",
        "KP": "Corea del Norte",
        "KR": "Corea del Sur",
        "CI": "Costa de Marfil",
        "CR": "Costa Rica",
        "HR": "Croacia",
        "CU": "Cuba",
        "DK": "Dinamarca",
        "DM": "Dominica",
        "EC": "Ecuador",
        "EG": "Egipto",
        "SV": "El Salvador",
        "AE": "Emiratos Árabes Unidos",
        "ER": "Eritrea",
        "SK": "Eslovaquia",
        "SI": "Eslovenia",
        "ES": "España",
        "US": "Estados Unidos de América",
        "EE": "Estonia",
        "ET": "Etiopía",
        "PH": "Filipinas",
        "FI": "Finlandia",
        "FJ": "Fiyi",
        "FR": "Francia",
        "GA": "Gabón",
        "GM": "Gambia",
        "GE": "Georgia",
        "GH": "Ghana",
        "GI": "Gibraltar",
        "GD": "Granada",
        "GR": "Grecia",
        "GL": "Groenlandia",
        "GP": "Guadalupe",
        "GU": "Guam",
        "GT": "Guatemala",
        "GF": "Guayana Francesa",
        "GG": "Guernsey",
        "GN": "Guinea",
        "GQ": "Guinea Ecuatorial",
        "GW": "Guinea-Bissau",
        "GY": "Guyana",
        "HT": "Haití",
        "HN": "Honduras",
        "HK": "Hong kong",
        "HU": "Hungría",
        "IN": "India",
        "ID": "Indonesia",
        "IR": "Irán",
        "IQ": "Irak",
        "IE": "Irlanda",
        "BV": "Isla Bouvet",
        "IM": "Isla de Man",
        "CX": "Isla de Navidad",
        "NF": "Isla Norfolk",
        "IS": "Islandia",
        "BM": "Islas Bermudas",
        "KY": "Islas Caimán",
        "CC": "Islas Cocos (Keeling)",
        "CK": "Islas Cook",
        "AX": "Islas de Åland",
        "FO": "Islas Feroe",
        "GS": "Islas Georgias del Sur y Sandwich del Sur",
        "HM": "Islas Heard y McDonald",
        "MV": "Islas Maldivas",
        "FK": "Islas Malvinas",
        "MP": "Islas Marianas del Norte",
        "MH": "Islas Marshall",
        "PN": "Islas Pitcairn",
        "SB": "Islas Salomón",
        "TC": "Islas Turcas y Caicos",
        "UM": "Islas Ultramarinas Menores de Estados Unidos",
        "VG": "Islas Vírgenes Británicas",
        "VI": "Islas Vírgenes de los Estados Unidos",
        "IL": "Israel",
        "IT": "Italia",
        "JM": "Jamaica",
        "JP": "Japón",
        "JE": "Jersey",
        "JO": "Jordania",
        "KZ": "Kazajistán",
        "KE": "Kenia",
        "KG": "Kirgizstán",
        "KI": "Kiribati",
        "KW": "Kuwait",
        "LB": "Líbano",
        "LA": "Laos",
        "LS": "Lesoto",
        "LV": "Letonia",
        "LR": "Liberia",
        "LY": "Libia",
        "LI": "Liechtenstein",
        "LT": "Lituania",
        "LU": "Luxemburgo",
        "MX": "México",
        "MC": "Mónaco",
        "MO": "Macao",
        "MK": "Macedônia",
        "MG": "Madagascar",
        "MY": "Malasia",
        "MW": "Malawi",
        "ML": "Mali",
        "MT": "Malta",
        "MA": "Marruecos",
        "MQ": "Martinica",
        "MU": "Mauricio",
        "MR": "Mauritania",
        "YT": "Mayotte",
        "FM": "Micronesia",
        "MD": "Moldavia",
        "MN": "Mongolia",
        "ME": "Montenegro",
        "MS": "Montserrat",
        "MZ": "Mozambique",
        "NA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NI": "Nicaragua",
        "NE": "Niger",
        "NG": "Nigeria",
        "NU": "Niue",
        "NO": "Noruega",
        "NC": "Nueva Caledonia",
        "NZ": "Nueva Zelanda",
        "OM": "Omán",
        "NL": "Países Bajos",
        "PK": "Pakistán",
        "PW": "Palau",
        "PS": "Palestina",
        "PA": "Panamá",
        "PG": "Papúa Nueva Guinea",
        "PY": "Paraguay",
        "PE": "Perú",
        "PF": "Polinesia Francesa",
        "PL": "Polonia",
        "PT": "Portugal",
        "PR": "Puerto Rico",
        "QA": "Qatar",
        "GB": "Reino Unido",
        "CF": "República Centroafricana",
        "CZ": "República Checa",
        "DO": "República Dominicana",
        "RE": "Reunión",
        "RW": "Ruanda",
        "RO": "Rumanía",
        "RU": "Rusia",
        "EH": "Sahara Occidental",
        "WS": "Samoa",
        "AS": "Samoa Americana",
        "BL": "San Bartolomé",
        "KN": "San Cristóbal y Nieves",
        "SM": "San Marino",
        "MF": "San Martín (Francia)",
        "PM": "San Pedro y Miquelón",
        "VC": "San Vicente y las Granadinas",
        "SH": "Santa Elena",
        "LC": "Santa Lucía",
        "ST": "Santo Tomé y Príncipe",
        "SN": "Senegal",
        "RS": "Serbia",
        "SC": "Seychelles",
        "SL": "Sierra Leona",
        "SG": "Singapur",
        "SY": "Siria",
        "SO": "Somalia",
        "LK": "Sri lanka",
        "ZA": "Sudáfrica",
        "SD": "Sudán",
        "SE": "Suecia",
        "CH": "Suiza",
        "SR": "Surinám",
        "SJ": "Svalbard y Jan Mayen",
        "SZ": "Swazilandia",
        "TJ": "Tadjikistán",
        "TH": "Tailandia",
        "TW": "Taiwán",
        "TZ": "Tanzania",
        "IO": "Territorio Británico del Océano Índico",
        "TF": "Territorios Australes y Antárticas Franceses",
        "TL": "Timor Oriental",
        "TG": "Togo",
        "TK": "Tokelau",
        "TO": "Tonga",
        "TT": "Trinidad y Tobago",
        "TN": "Tunez",
        "TM": "Turkmenistán",
        "TR": "Turquía",
        "TV": "Tuvalu",
        "UA": "Ucrania",
        "UG": "Uganda",
        "UY": "Uruguay",
        "UZ": "Uzbekistán",
        "VU": "Vanuatu",
        "VE": "Venezuela",
        "VN": "Vietnam",
        "WF": "Wallis y Futuna",
        "YE": "Yemen",
        "DJ": "Yibuti",
        "ZM": "Zambia",
        "ZW": "Zimbabue"
    }
};

